---
- block:
    - name: 'Check mandatory variables are defined'
      assert:
        that:
          - password_plaintext is defined

    - name: Import tasks
      import_tasks: copy_files.yml
    - name: Import tasks
      import_tasks: resources.yml
    - name: Import tasks
      import_tasks: default_tls.yml
    - name: Import tasks
      import_tasks: deploy.yml
    - name: Import tasks
      import_tasks: loadbalancer.yml
  when:
    - k8s_enabled|bool
    - ingress_enabled|bool
