---
- name: Converge Observability cluster
  hosts: localhost
  connection: local
  gather_facts: true
  environment:
    HOME: "{{ build_dir }}"
    PATH: "{{ build_dir }}/bin:{{ lookup('env','PATH') }}"
  vars_files:
    - "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/cluster-config-01.yml"
  roles:
    - role: oblt.framework.tools

    - role: oblt.framework.common
  tasks:
    - name: Deploy Stack
      include_role:
        name: oblt.framework.stack_ess
    - name: Set Cluster Id fact
      set_fact:
        cluster_01_name: "{{ cluster_name }}"
        cluster_01_id: "{{ ess_deployment_id }}"
        observability_secret: "{{ secret_root_gcsm }}_{{ cluster_name }}_cluster-state"
    - name: Set cluster created flag
      set_fact:
        cluster_created: true
    - name: Vault Secrets
      include_role:
        name: oblt.framework.common
        tasks_from: cluster_state.yml

- name: Converge data cluster
  hosts: localhost
  connection: local
  gather_facts: true
  environment:
    HOME: "{{ build_dir }}"
    PATH: "{{ build_dir }}/bin:{{ lookup('env','PATH') }}"
  vars_files:
    - "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/cluster-config-02.yml"
  roles:
    - role: oblt.framework.tools

    - role: oblt.framework.common
  tasks:
    - name: Debug secret name
      debug:
        msg: "observability_secret: {{ observability_secret }}"
    - name: Deploy Stack
      include_role:
        name: oblt.framework.stack_ess
    - name: Set cluster created flag
      set_fact:
        cluster_created: true
    - name: Vault Secrets
      include_role:
        name: oblt.framework.common
        tasks_from: cluster_state.yml
