---
- name: Custom Destroy
  hosts: localhost
  connection: local
  gather_facts: true
  environment:
    HOME: "{{ build_dir }}"
    PATH: "{{ build_dir }}/bin:{{ lookup('env','PATH') }}"
  vars_files:
    - "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/cluster-config-01.yml"
  roles:
    - role: oblt.framework.tools

    - role: oblt.framework.common
  tasks:
    - name: Set Cluster Id fact
      set_fact:
        cluster_01_name: "{{ cluster_name }}"
    - name: Import role
      include_role:
        name: oblt.framework.stack_ess
        tasks_from: destroy_cluster.yml
        apply:
          ignore_errors: true
    - name: Import role
      include_role:
        name: oblt.framework.common
        tasks_from: delete_secrets.yml
        apply:
          ignore_errors: true

- name: Custom Destroy
  hosts: localhost
  connection: local
  gather_facts: true
  environment:
    HOME: "{{ build_dir }}"
    PATH: "{{ build_dir }}/bin:{{ lookup('env','PATH') }}"
  vars_files:
    - "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/cluster-config-02.yml"
  roles:
    - role: oblt.framework.tools

    - role: oblt.framework.common
  tasks:
    - name: Import role
      include_role:
        name: oblt.framework.stack_ess
        tasks_from: destroy_cluster.yml
        apply:
          ignore_errors: true
    - name: Import role
      include_role:
        name: oblt.framework.common
        tasks_from: delete_secrets.yml
        apply:
          ignore_errors: true
