{{- if (not .Values.obltCluster) }}
---
kind: SecretClaim
apiVersion: vaultproject.io/v1
metadata:
  name: {{ .Chart.Name }}-es-creds
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
spec:
  type: Opaque
  path: secret/k8s/eden/{{ .Values.environment }}/{{ .Chart.Name }}/{{ .Values.username }}/es
---
kind: SecretClaim
apiVersion: vaultproject.io/v1
metadata:
  name: {{ .Chart.Name }}-kibana-creds
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
spec:
  type: Opaque
  path: secret/k8s/eden/{{ .Values.environment }}/{{ .Chart.Name }}/{{ .Values.username }}/kibana
---
kind: SecretClaim
apiVersion: vaultproject.io/v1
metadata:
  name: {{ .Chart.Name }}-apm-creds
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
spec:
  type: Opaque
  path: secret/k8s/eden/{{ .Values.environment }}/{{ .Chart.Name }}/{{ .Values.username }}/apm
---
kind: SecretClaim
apiVersion: vaultproject.io/v1
metadata:
  name: {{ .Chart.Name }}-fleet-creds
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
spec:
  type: Opaque
  path: secret/k8s/eden/{{ .Values.environment }}/{{ .Chart.Name }}/{{ .Values.username }}/fleet
---
kind: SecretClaim
apiVersion: vaultproject.io/v1
metadata:
  name: {{ .Chart.Name }}-mail-creds
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
spec:
  type: Opaque
  path: secret/k8s/eden/{{ .Values.environment }}/{{ .Chart.Name }}/mail
{{- else }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-es-creds
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
type: Opaque
stringData:
  ELASTICSEARCH_PASSWORD: "{{ .Values.elasticsearch_password }}"
  ELASTICSEARCH_URL: "{{ .Values.elasticsearch_url }}"
  ELASTICSEARCH_USERNAME: "{{ .Values.elasticsearch_username }}"
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-kibana-creds
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
type: Opaque
stringData:
  KIBANA_URL: "{{ .Values.kibana_url }}"
  KIBANA_USERNAME: "{{ .Values.kibana_username }}"
  KIBANA_PASSWORD: "{{ .Values.kibana_password }}"
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-apm-creds
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
type: Opaque
stringData:
  APM_URL: "{{ .Values.apm_url }}"
  APM_SECRET_TOKEN: "{{ .Values.apm_token }}"
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-fleet-creds
  namespace: {{ .Chart.Name }}-{{ .Values.username }}
type: Opaque
stringData:
  FLEET_URL: "{{ .Values.fleet_url }}"
{{- end }}
