{{ if .Values.certmanager.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: {{ .Values.projectName }}
  source:
    # https://cert-manager.io/docs/troubleshooting/webhook/#error-io-timeout-connectivity-issue
    # Autopilot fixes
    # https://github.com/cert-manager/cert-manager/issues/4646#issuecomment-1023741490
    # https://github.com/cert-manager/cert-manager/issues/3717#issuecomment-931567578
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: {{ .Values.certmanager.version }}
    helm:
      releaseName: cert-manager
      valuesObject:
        global:
          leaderElection:
            namespace: {{ .Values.certmanager.namespace }}
        startupapicheck:
          startupapicheck: 10m
        installCRDs: true
        ingressShim:
          defaultIssuerName: {{ .Values.certmanager.issuer }}
          defaultIssuerKind: ClusterIssuer
        resources:
          requests:
            cpu: 0.1
            memory: "64Mi"
          limits:
            memory: "128Mi"
        webhook:
          hostNetwork: true
          securePort: 10260
          resources:
            requests:
              cpu: 0.1
              memory: "64Mi"
            limits:
              memory: "128Mi"
        cainjector:
          resources:
            requests:
              cpu: 0.1
              memory: "64Mi"
            limits:
              memory: "256Mi"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.certmanager.namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
{{- end }}
