{{ if .Values.externalSecrets.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: {{ .Values.projectName }}
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: {{ .Values.externalSecrets.version }}
    helm:
      releaseName: external-secrets
      valuesObject:
        serviceAccount:
          create: true
          automount: true
          name: external-secrets-default
          annotations:
            {{- toYaml .Values.externalSecrets.serviceAccount.annotations | nindent 12 }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.externalSecrets.namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
{{- end }}
