---
- name: Patch ECK resources
  changed_when: false
  vars:
    patch:
      spec:
        secureSettings:
          - secretName: gcs-credentials-file
  shell: |
    kubectl delete secret gcs-credentials-file || true
    kubectl create secret generic gcs-credentials-file --from-file=gcs.client.external.credentials_file={{ build_dir }}/gcp/credentials.json
    kubectl patch elasticsearch elastic-stack --patch '{{ patch | to_json }}' --type merge
    sleep 15
  when:
    - elasticsearch_type == 'eck'

- name: Include tasks from wait-for-es-green.yml
  include_tasks: "wait-for-es-green.yml"
