---
- name: set Environment variables for the Elasticsearch
  set_fact:
    elastic_stack_es_env:
      CLUSTER_NAME: "{{ cluster_name }}"
      # TODO add CLUSTER_UUID
      ELASTICSEARCH_HOSTS: "{{ elasticsearch_url }}"
      ELASTICSEARCH_HOST: "{{ elasticsearch_url }}"
      ELASTICSEARCH_USERNAME: "{{ elasticsearch_username }}"
      ELASTICSEARCH_PASSWORD: "{{ elasticsearch_password }}"
  when:
    - elasticsearch_enabled|bool

- name: set Environment variables for the Kibana
  set_fact:
    elastic_stack_kbn_env:
      KIBANA_HOST: "{{ kibana_url if kibana_enabled }}"
      KIBANA_HOSTS: "{{ kibana_url if kibana_enabled }}"
      KIBANA_FLEET_HOST: "{{ kibana_url if kibana_enabled }}"
      KIBANA_USERNAME: "{{ kibana_username if kibana_enabled }}"
      KIBANA_PASSWORD: "{{ kibana_password if kibana_enabled }}"
  when:
    - kibana_enabled|bool

- name: set Environment variables for the APM
  set_fact:
    elastic_stack_apm_env:
      ELASTIC_APM_SERVER_URL: "{{ apm_url if apm_enabled }}"
      ELASTIC_APM_JS_SERVER_URL: "{{ apm_url if apm_enabled }}"
      ELASTIC_APM_JS_BASE_SERVER_URL: "{{ apm_url if apm_enabled }}"
      ELASTIC_APM_SECRET_TOKEN: "{{ apm_token if apm_enabled }}"
      ELASTIC_APM_SERVER_HOST_PORT: "{{ apm_url | urlsplit('hostname') }}:{{ apm_url | urlsplit('port') | default('443') }}"
  when:
    - apm_enabled|bool

- name: set Environment variables for the Fleet
  set_fact:
    elastic_stack_fleet_env:
      FLEET_ELASTICSEARCH_HOST: "{{ elasticsearch_url  if fleet_enabled }}"
      FLEET_ENROLLMENT_TOKEN: "{{ fleet_enroll_token if fleet_enabled }}"
      FLEET_SERVER_SERVICE_TOKEN: "{{ fleet_server_token if fleet_enabled }}"
      FLEET_SERVER_POLICY_ID: "{{ fleet_server_policy_id if fleet_enabled }}"
      FLEET_TOKEN_POLICY_NAME: "{{ fleet_policy_id if fleet_enabled }}"
      FLEET_URL: "{{ fleet_url if fleet_enabled }}"
      ELASTICSEARCH_API_TOKEN: "{{ fleet_api_token if fleet_enabled }}"
  when:
    - fleet_enabled|bool

- name: Create k8s Secrets
  vars:
    secrets_namespace: "{{ item.namespace }}"
  k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', '{{ templates_dir }}/stack_secrets_{{ item.secret }}.yaml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
  loop:
    - secret: elasticsearch
      namespace: "{{ k8s_default_namespace }}"
    - secret: elasticsearch
      namespace: "{{ kube_system_namespace }}"
    - secret: kibana
      namespace: "{{ k8s_default_namespace }}"
    - secret: kibana
      namespace: "{{ kube_system_namespace }}"
    - secret: apm
      namespace: "{{ k8s_default_namespace }}"
    - secret: apm
      namespace: "{{ kube_system_namespace }}"
    - secret: fleet
      namespace: "{{ k8s_default_namespace }}"
    - secret: fleet
      namespace: "{{ kube_system_namespace }}"
  tags:
    - secrets
    - deploy
