---
- name: Destroy k8s cluster (GCP)
  ignore_errors: true
  block:
    - register: _result
      include_role:
        name: oblt.framework.k8s_gcp
        tasks_from: destroy_cluster.yml
  when:
    - k8s_enabled|bool
    - k8s_provider == 'gcp' or k8s_provider == 'autopilot'

- name: Destroy k8s cluster (Kind)
  ignore_errors: true
  block:
    - register: _result
      include_role:
        name: oblt.framework.k8s_kind
        tasks_from: destroy_cluster.yml
  when:
    - k8s_enabled|bool
    - k8s_provider == 'kind'

- name: Recreate k8s cluster
  include_tasks: k8s.yml

- name: Redeploy k8s deployments
  include_tasks: k8s-deployments.yml

- name: Redeploy EDEN demos
  include_tasks: eden.yml

- name: Include tasks from vault-secrets.yml
  include_tasks: vault-secrets.yml
  when:
    - save_secrets|bool
