---
- name: Add "Extract Device Type"
  uri:
    url: "{{ elasticsearch_url }}/_ingest/pipeline/apm_user_agent"
    method: PUT
    validate_certs: false
    user: "{{ elasticsearch_username }}"
    password: "{{ elasticsearch_password }}"
    force_basic_auth: true
    headers:
      Content-Type: application/json
      kbn-xsrf: true
    body: |
      {
        "description": "Add user agent information for APM events",
        "processors": [{
          "user_agent": {
            "field": "user_agent.original",
            "target_field": "user_agent",
            "ignore_missing": true,
            "extract_device_type": true,
            "ignore_failure": true
          }
        }]
      }
  register: _result_es
  until: _result_es.status == 200
  retries: 20
  delay: 15
  when:
    - elasticsearch_enabled

- name: Add Synthetics monitors
  vars:
    synthetics_monitor_id: "{{ item.id }}"
    synthetics_monitors_folder: "{{ item.folder }}"
    synthetics_monitors_params: "{{ item.params }}"
    synthetics_locale: "{{ item.locale | default('en-US') }}"
    synthetics_timezone: "{{ item.timezone | default('America/Los_Angeles') }}"
  include_tasks: synthetics-monitor.yml
  loop: "{{ synthetics_monitors_folders }}"
  loop_control:
    label: "{{ item.id }}"
  when:
    - kibana_enabled
    - synthetics_monitors_folders is defined
    - synthetics_monitors_folders | length > 0
