---
- name: Create build dir
  file:
    path: "{{ build_dir }}/bin"
    state: directory
    mode: '0755'

- name: Find User files
  find:
    paths: "{{ role_path }}/../roles/stack_security/templates/users"
  register: user_files

- name: set common fats
  set_fact:
    kibana_docker_image: "{{ ess_kb_image | default(None, true) }}"
    elasticsearch_docker_image: "{{ ess_es_image | default(None, true) }}"

- name: set Enfironment variables for ESS
  set_fact:
    ess_env:
      ESS_CLUSTER_ID: "{{ ess_cloud_id }}"
      ESS_DEPLOYMENT_ID: "{{ ess_deployment_id }}"
  when:
    - elasticsearch_enabled|bool
    - elasticsearch_type == 'ess'

- name: set Environment variables for the Ingress
  set_fact:
    ingress_env:
      INGRESS_USERNAME: "{{ ingress_username }}"
      INGRESS_PASSWORD: "{{ ingress_password }}"
  when:
    - ingress_enabled|bool

- name: set Environment variables for the Elasticsearch
  set_fact:
    elastic_stack_es_env:
      ELASTICSEARCH_HOSTS: "{{ elasticsearch_url }}"
      ELASTICSEARCH_HOST: "{{ elasticsearch_url }}"
      ELASTICSEARCH_USERNAME: "{{ elasticsearch_username }}"
      ELASTICSEARCH_PASSWORD: "{{ elasticsearch_password }}"
      ELASTICSEARCH_API_KEY: "{{ elasticsearch_apikey | default('') }}"
  when:
    - elasticsearch_enabled|bool

- name: set Environment variables for the Kibana
  set_fact:
    elastic_stack_kbn_env:
      KIBANA_HOST: "{{ kibana_url | default('') }}"
      KIBANA_HOSTS: "{{ kibana_url | default('') }}"
      KIBANA_FLEET_HOST: "{{ kibana_url | default('') }}"
      KIBANA_USERNAME: "{{ kibana_username | default('') }}"
      KIBANA_PASSWORD: "{{ kibana_password | default('') }}"
  when:
    - kibana_enabled|bool

- name: set Environment variables for the APM
  set_fact:
    elastic_stack_apm_env:
      ELASTIC_APM_SERVER_URL: "{{ apm_url | default('') }}"
      ELASTIC_APM_JS_SERVER_URL: "{{ apm_url | default('') }}"
      ELASTIC_APM_JS_BASE_SERVER_URL: "{{ apm_url | default('') }}"
      ELASTIC_APM_SECRET_TOKEN: "{{ apm_token | default('') }}"
      ELASTIC_APM_API_KEY: "{{ apm_apikey | default('') }}"
  when:
    - apm_enabled|bool

- name: set Environment variables for the Fleet
  set_fact:
    elastic_stack_fleet_env:
      FLEET_ELASTICSEARCH_HOST: "{{ elasticsearch_url  | default('') }}"
      FLEET_ENROLLMENT_TOKEN: "{{ fleet_enroll_token | default('') }}"
      FLEET_SERVER_SERVICE_TOKEN: "{{ fleet_server_token | default('') }}"
      FLEET_SERVER_POLICY_ID: "{{ fleet_server_policy_id | default('') }}"
      FLEET_TOKEN_POLICY_NAME: "{{ fleet_policy_id | default('') }}"
      FLEET_URL: "{{ fleet_url | default('') }}"
      ELASTICSEARCH_API_TOKEN: "{{ fleet_api_token | default('') }}"
  when:
    - fleet_enabled|bool

- name: "Create {{ build_dir }}/users.yml file"
  copy:
    content: "{{ lookup('ansible.builtin.template', '{{ templates_dir }}/user_msg.yml.j2') }}"
    dest: "{{ build_dir }}/users.yml"

- name: "Create {{ build_dir }}/kibana.yml file"
  copy:
    content: "{{ lookup('ansible.builtin.template', '{{ templates_dir }}/kibana.yml.j2') }}"
    dest: "{{ build_dir }}/kibana.yml"

- name: "Create deploy-info.md file"
  vars:
    slack: false
  copy:
    content: "{{ lookup('ansible.builtin.template', '{{ templates_dir }}/deploy_info_msg.yml.j2') }}"
    dest: "{{ build_dir }}/deploy-info.md"

- name: "Create deploy-info-slack.json file"
  vars:
    slack: true
  copy:
    content: "{{ lookup('ansible.builtin.template', '{{ templates_dir }}/deploy_info_msg_slack.json.j2') }}"
    dest: "{{ build_dir }}/deploy-info-slack.json"

- name: "Create {{ build_dir }}/credentials.md file"
  vars:
    slack: false
  copy:
    content: "{{ lookup('ansible.builtin.template', '{{ templates_dir }}/credentials_msg.yml.j2') }}"
    dest: "{{ build_dir }}/credentials.md"

- name: "Create {{ build_dir }}/activate-k8s file"
  copy:
    content: "{{ lookup('ansible.builtin.template', '{{ templates_dir }}/activate-k8s.j2') }}"
    dest: "{{ build_dir }}/activate-k8s"
  # when:
  #   - k8s_enabled | bool

- name: Cluster State Vault Secret
  include_role:
    name: oblt.framework.common
    tasks_from: cluster_state.yml

- name: "Store secrets in Google Secret Manager"
  oblt.framework.gcp_secret_manager:
    name: "{{ item.key }}"
    state: present
    value: "{{ item.content }}"
    labels:
      cluster_name: "{{ cluster_name }}"
      name: "{{ item.name }}"
      ephemeral: "{{ 'yes' if ephemeral_cluster else 'no' }}"
  loop_control:
    label: "{{ item.name }}"
  loop:
    - name: activate-k8s
      content: "{{ lookup('file', '{{ build_dir }}/activate-k8s') | default('# Empty') }}"
      key: "{{ activate_gcsm_def_secret }}"
    - name: env
      content: "{{ lookup('ansible.builtin.template', '{{ templates_dir }}/env.j2') }}"
      key: "{{ elastic_stack_env_gcsm_def_secret }}"
    - name: credentials
      content: "{{ lookup('file', '{{ build_dir }}/credentials.md') }}"
      key: "{{ credentials_gcsm_def_secret }}"
    - name: deploy-info
      content: "{{ lookup('file', '{{ build_dir }}/deploy-info.md') }}"
      key: "{{ deploy_info_gcsm_def_secret }}"
    - name: kibana-yml
      content: "{{ lookup('file', '{{ build_dir }}/kibana.yml') }}"
      key: "{{ kibana_yml_gcsm_def_secret }}"
  when:
    - save_secrets|bool
