---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    build_dir: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/build"
    hermit_enabled: true
    k8s_provider: kind
    k8s_enabled: true
    save_secrets: false
  environment:
    PATH: "{{ build_dir }}/bin:{{ build_dir }}/bin/google-cloud-sdk/bin:{{ lookup('env','PATH') }}"
  roles:
    - role: oblt.framework.tools
