cluster_name: "oblt-test-{{ cluster_seed }}"
save_secrets: true
deploy_timestamp: foo #always the same to check the idenpotence.
ephemeral_cluster: true
build_dir: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/build"

stack:
  mode: serverless
  template: security
  target: qa
