version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/tools/oblt-cli"
      - "/tools/oblt-robot"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/ansible"
    schedule:
      interval: "weekly"
    groups:
      ansible:
        patterns:
          - "ansible*"
      click:
        patterns:
          - "click*"
      molecule:
        patterns:
          - "molecule*"
