---
- name: Get GCP cluster credentials
  changed_when: false
  command: |
    gcloud container clusters get-credentials "{{ gke_cluster_name }}" \
      --zone "{{ k8s_region }}" --project "{{ k8s_project }}"
  tags:
    - auth
    - gcp
