# yaml-language-server: $schema=../../../../docs/cluster-config-schema.json
cluster_name: apm-oblt
slack_channel: "#observablt-bots"
oblt_username: "robots"
configure_external_snapshots_repo_ro: true
create_users: false
grab_cluster_info: true
golden_cluster: true
stack:
  version: 8.15.0
  mode: ess
  template: observability
  target: production
  observability: true
  update_channel: release
  update_schedule: tuesday
  ess:
    saml_id: exks9x4l96fgLB6Aj1t7
    template: 'gcp-storage-optimized'
    elasticsearch:
      image: docker.elastic.co/observability-ci/elasticsearch-cloud-ess:8.15.0-474303bf
      max_mem: 128
    kibana:
      image: docker.elastic.co/observability-ci/kibana-cloud:8.15.0-474303bf
    integrations:
      image: docker.elastic.co/observability-ci/elastic-agent-cloud:8.15.0-474303bf
    profiling:
      image: docker.elastic.co/observability-ci/profiling-agent:8.15.0-474303bf
updated_at: "2024-08-06T02:17:27Z"
