---
- name: Set default context namespace
  changed_when: false
  command: |
    kubectl config set-context --current \
      --namespace={{ k8s_default_namespace }}
  tags:
    - deploy
    - kind
    - k8s
