---
cluster_name: "oblt-test-{{ cluster_seed }}"
ephemeral_cluster: true
build_dir: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/build"

stack:
  mode: external
  external:
    secret: "oblt-clusters_edge-oblt_cluster-state"
