---
- name: Custom Destroy
  hosts: localhost
  connection: local
  gather_facts: true
  environment:
    HOME: "{{ build_dir }}"
    PATH: "{{ build_dir }}/bin:{{ lookup('env','PATH') }}"
  vars_files:
    - "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/cluster-config.yml"
  roles:
    - role: oblt.framework.tools
    - role: oblt.framework.common
  tasks:
    - name: Import role
      include_role:
        name: oblt.framework.k8s_kind
        tasks_from: check_cluster_created.yml
    - name: Import role
      include_role:
        name: oblt.framework.k8s_ingress
        tasks_from: undeploy.yml
      when:
        - kind_cluster_available.stdout_lines
    - name: Import role
      include_role:
        name: oblt.framework.k8s_kind
        tasks_from: destroy_cluster_all.yml
