---
galaxy_info:
  role_name: stack_ess
  author: Elastic
  namespace: elastic
  description: AQA (Automation and Quality Assistance)
  company: Elastic
  license: Elastic
  platforms:
   - name: Ubuntu
  galaxy_tags:
    - oblt
    - elastic
  min_ansible_version: 2.9
