cluster_name: "oblt-test-{{ cluster_seed }}"
save_secrets: true
deploy_timestamp: foo #always the same to check the idenpotence.
build_dir: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/build"
ephemeral_cluster: true
ess_not_allow_settings: false
stack:
  mode: "ess"
  template: "observability"
  target: "staging"

k8s:
  provider: kind
