---
# yaml-language-server: $schema=./values.schema.json
## @section opbeans Opbeans Frontend Helm chart configuration
opbeans:
  ## @param opbeans.enabled Enable or disable the whole kubernetes deployments, this allow to use it on parent charts.
  enabled: true
  ## @param opbeans.nameOverride Overrides the the Helm Chart name used to naming kubernetes objects, by default `opbeans`.
  nameOverride: ""
  ## @param opbeans.fullnameOverride Overrides the the Helm Chart fullname used to naming kubernetes objects, by default `opbeanst`.
  fullnameOverride: ""
  ## @section opbeans.image Docker image settings
  image:
    ## @param opbeans.image.name Name of the Docker image (docker.elastic.co/observability-ci/it_opbeans-frontend_nginx).
    ## @param opbeans.image.tag Tag of the Docker image (latest).
    ## @param opbeans.image.pullPolicy Docker image pull policy (IfNotPresent|Always|Never)
    name: docker.elastic.co/observability-ci/opbeans-frontend
    tag: daily
    pullPolicy: IfNotPresent
  ## @section apm APM configuration settings.
  apm:
    ## @param opbeans.apm.type Type of reporting API [apm|otel|annotations]
    ## @param opbeans.apm.annotationType Type of annotations to use [none|nodejs|java]
    type: annotations
    annotationType: nodejs
    ## @param opbeans.apm.enabled [boolean,nullable] Enable to send data to the APM service.
    enabled: true

  ## @section ingress Ingress settings
  ingress:
    ## @param opbeans.ingress.enabled Enable or disable the ingress resource.
    ## @param opbeans.ingress.certificateIssuer Name of the certificates issuer.
    ## @param opbeans.ingress.host Hostname exposed by the ingress resource.
    ## @param opbeans.ingress.annotations Additional annotation to the ingress resource.
    enabled: true
    certificateIssuer: "letsencrypt-stage"
    host: opbeans-frontend.127.0.0.1.ip.es.io
    ## @skip opbeans.ingress.annotations
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/app-root: /dashboard
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: elastic-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
  ## @section resources requests and limits
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ## @param opbeans.resources.limits.memory The memory limit for the Opbean
  ## @param opbeans.resources.requests.memory The requested memory for the Opbean
  ## @param opbeans.resources.requests.cpu The requested cpu for the Opbean
  resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 0.1
        memory: 512Mi
