//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// ClusterConfig defines model for ClusterConfig.
type ClusterConfig struct {
	Apps *struct {
		// Helm Chart to deploy
		Helm *[]struct {
			// Chart Chart to deploy
			Chart *string `json:"chart,omitempty"`

			// Name Name of the Helm chart
			Name *string `json:"name,omitempty"`

			// Namespace Namespace to deploy the chart
			Namespace *string `json:"namespace,omitempty"`

			// ValuesFile Values file for the Helm chart
			ValuesFile *string `json:"values_file,omitempty"`

			// Version Version of the chart
			Version *string `json:"version,omitempty"`
		} `json:"helm,omitempty"`

		// K8s Name of the Kubernetes manifest
		K8s *[]struct {
			// Name Name of the Kubernetes manifest
			Name *string `json:"name,omitempty"`

			// Src Source directory for the Kubernetes manifest
			Src *string `json:"src,omitempty"`
		} `json:"k8s,omitempty"`
	} `json:"apps,omitempty"`

	// BootstrapCluster True to bootstrap the cluster (default: false) see [bootstrap](./bootstrap.md)
	BootstrapCluster *bool `json:"bootstrap_cluster,omitempty"`

	// BootstrapClusterDirs Directories where the bootstrap cluster are located.
	BootstrapClusterDirs *[]interface{} `json:"bootstrap_cluster_dirs,omitempty"`

	// BuildTfProviderFromSrc True to build the Elastic terraform provider from source (default: fatse).
	BuildTfProviderFromSrc *bool `json:"build_tf_provider_from_src"`

	// ClusterName Name of the cluster (e.g. sample-oblt)
	ClusterName *string `json:"cluster_name,omitempty"`

	// ConfigureExternalSnapshotsRepo True to configure an external snapshot repository (default: false)
	ConfigureExternalSnapshotsRepo *bool `json:"configure_external_snapshots_repo,omitempty"`

	// CreateUsers True to create users for the cluster (default: true)
	CreateUsers *bool `json:"create_users,omitempty"`

	// EssNotAllowSettings True to disable some settings not allowed in staging.
	EssNotAllowSettings *bool `json:"ess_not_allow_settings,omitempty"`

	// EssTerraformVersion Version of the Elastic terraform provider to use (default: 0.5.0)
	EssTerraformVersion *string `json:"ess_terraform_version,omitempty"`

	// ExpireDate Date to expire the cluster (e.g. 2023-12-31).
	ExpireDate *string        `json:"expire_date,omitempty"`
	Features   *[]interface{} `json:"features,omitempty"`

	// GoldenCluster True to create a golden cluster (default: false)
	GoldenCluster *bool `json:"golden_cluster,omitempty"`

	// GrabClusterInfo True to grab cluster information (default: true)
	GrabClusterInfo *bool `json:"grab_cluster_info,omitempty"`
	K8s             *struct {
		// CertificateIssuer Issuer of the certificate, e.g. letsencrypt-prod, letsencrypt-staging (default: letsencrypt-staging)
		CertificateIssuer *string `json:"certificate_issuer,omitempty"`

		// Certmanager True to enable cert-manager
		Certmanager *bool `json:"certmanager"`

		// ClusterName Name of the k8s cluster, it replaces de default name (default: {{ cluster_name }})
		ClusterName *string `json:"cluster_name,omitempty"`

		// DefaultNamespace Default namespace for all resources
		DefaultNamespace *string `json:"default_namespace,omitempty"`

		// Domain Domain name for the cluster
		Domain *string `json:"domain,omitempty"`

		// Enabled True to enable Kubernetes cluster creation
		Enabled *bool `json:"enabled"`

		// Ingress True to enable ingress controller
		Ingress *bool `json:"ingress"`

		// KubeSystemNamespace Namespace for the kube-system resources
		KubeSystemNamespace *string `json:"kube_system_namespace,omitempty"`

		// MachineType Machine type, e.g. n1-standard-4
		MachineType *string `json:"machine_type,omitempty"`

		// MaxNodeCount Maximum number of nodes
		MaxNodeCount *float32 `json:"max_node_count"`

		// Network Network to use for the cluster
		Network *string `json:"network,omitempty"`

		// Project Project name
		Project *string `json:"project,omitempty"`

		// Provider Cloud provider, e.g. gcp, kind
		Provider *string `json:"provider,omitempty"`

		// Region Cloud region, e.g. us-east-1, europe-west1-c
		Region *string `json:"region,omitempty"`

		// Shared Name of the shared cluster.This is used to share the same cluster between different deployments, when is set a cluster is not created.
		Shared *string `json:"shared,omitempty"`

		// StaticIp True to enable static IP
		StaticIp *bool `json:"static_ip"`
	} `json:"k8s,omitempty"`

	// LoadBalancerIp Loadbalancer IP to use for the cluster
	LoadBalancerIp *string `json:"load_balancer_ip,omitempty"`

	// ObltUsername Username to use for the observability team (default: robots)
	ObltUsername *string `json:"oblt_username,omitempty"`

	// ObservabilitySecret Secret name for the observability cluster (default: oblt-clusters_monitoring-oblt)
	ObservabilitySecret *string `json:"observability_secret,omitempty"`
	Opbeans             *struct {
		// Enabled True to deploy Opbeans (default: false)
		Enabled *bool `json:"enabled,omitempty"`
	} `json:"opbeans,omitempty"`

	// ProfilingAgentDeploy True to deploy the profiling agent in the k8s cluster (default: true)
	ProfilingAgentDeploy *bool `json:"profiling_agent_deploy,omitempty"`

	// SecretEssUser path to the secret that contains the ESS credentials (elastic-cloud-observability-team-pro)
	SecretEssUser *string `json:"secret_ess_user,omitempty"`

	// SlackChannel Slack channel to use for notifications
	SlackChannel *string `json:"slack_channel,omitempty"`
	Stack        *struct {
		Eck *struct {
			Agent *struct {
				// Enabled True to enable Elastic Agent deployment (default: true)
				Enabled *bool `json:"enabled"`

				// Image Docker image for Elastic Agent (optional)
				Image *string `json:"image,omitempty"`

				// Mem Memory for Elastic Agent (default: 2)
				Mem *float32 `json:"mem"`
			} `json:"agent,omitempty"`
			Elasticsearch *struct {
				// Enabled True to enable Elasticsearch deployment (default: true)
				Enabled *bool `json:"enabled"`

				// Image Docker image for Elasticsearch (optional)
				Image *string `json:"image,omitempty"`

				// Mem Memory for Elasticsearch (default: 16)
				Mem *float32 `json:"mem"`

				// NodeCount Number of nodes for the Elasticsearch deployment (default: 3)
				NodeCount *float32 `json:"node_count"`

				// NodeStorage Size of the storage for each node (default: 256)
				NodeStorage *float32 `json:"node_storage"`
			} `json:"elasticsearch,omitempty"`
			Kibana *struct {
				// Enabled True to enable Kibana deployment (default: true)
				Enabled *bool `json:"enabled"`

				// FurtherDetails Message to show in the Kibana login page (optional)
				FurtherDetails *string `json:"further_details,omitempty"`

				// Image Docker image for Kibana (optional)
				Image *string `json:"image,omitempty"`

				// Mem Memory for Kibana (default: 2)
				Mem *float32 `json:"mem"`
			} `json:"kibana,omitempty"`

			// License License to use for ECK (default: trial) ['enterprise', 'trial', 'none']
			License *string `json:"license,omitempty"`
		} `json:"eck,omitempty"`
		Ess *struct {
			// Autoscale True to enable autoscaling (default: true)
			Autoscale *bool `json:"autoscale"`

			// CcsRemoteClusters List of remote clusters to configure CCS (optional)
			CcsRemoteClusters *[]interface{} `json:"ccs_remote_clusters,omitempty"`
			Elasticsearch     *struct {
				// Enabled True to enable Elasticsearch deployment (default: true)
				Enabled *bool `json:"enabled"`

				// Image Docker image for Elasticsearch (optional)
				Image *string `json:"image,omitempty"`

				// Mem Memory for Elasticsearch (default: 16)(ignored on autoscaling enabled)
				Mem *float32 `json:"mem"`

				// Zones Number of zones to use for the Elasticsearch deployment (default: 3)
				Zones *float32 `json:"zones"`
			} `json:"elasticsearch,omitempty"`
			Integrations *struct {
				// Enabled True to enable Integrations server deployment (default: true)
				Enabled *bool `json:"enabled"`

				// Image Docker image for Elastic Agent (optional)
				Image *string `json:"image,omitempty"`

				// Mem Memory for Integrations server (default: 2)(ignored on autoscaling enabled)
				Mem *float32 `json:"mem"`

				// Zones Number of zones to use for the Integrations serve deployment (default: 1)
				Zones *float32 `json:"zones"`
			} `json:"integrations,omitempty"`
			Kibana *struct {
				// Enabled True to enable Kibana deployment (default: true)
				Enabled *bool `json:"enabled"`

				// FurtherDetails Message to show in the Kibana login page (optional)
				FurtherDetails *string `json:"further_details,omitempty"`

				// Image Docker image for Kibana (optional)
				Image *string `json:"image,omitempty"`

				// Mem Memory for Kibana (default: 2)(ignored on autoscaling enabled)
				Mem *float32 `json:"mem"`

				// OpenAiSecret Vault secret with the OpenaAI connection information '{"apiKey":"XXXXXXX", "service": "azureOpenAI"}', '{"apiKey":"XXXXXXX", "service": "openAI"}'
				OpenAiSecret *string `json:"open_ai_secret,omitempty"`

				// Zones Number of zones to use for the Kibana deployment (default: 1)
				Zones *float32 `json:"zones"`
			} `json:"kibana,omitempty"`
			Profiling *struct {
				// Enabled True to enable profiling (default: false)
				Enabled *bool `json:"enabled"`

				// Image Docker image for profiling (optional)
				Image *string `json:"image,omitempty"`
			} `json:"profiling,omitempty"`

			// Provider Cloud provider, e.g. gcp, aws, azure (default: gcp)
			Provider *string `json:"provider,omitempty"`

			// Region Cloud region, e.g. us-east-1, europe-west1-c, gcp-us-west2, azure-eastus2,  (default: us-central1-c)
			Region *string `json:"region,omitempty"`

			// ResetPassword True to reset the password for the ESS deployment (default: false)
			ResetPassword *bool `json:"reset_password"`

			// RestoreSnapshotFrom Restore a snapshot from a given deployment ID (optional)
			RestoreSnapshotFrom *string `json:"restore_snapshot_from,omitempty"`

			// RestoreSnapshotName Name of the snapshot to restore (optional)(default: __latest_success__)
			RestoreSnapshotName *string `json:"restore_snapshot_name,omitempty"`

			// SamlId Service Provider (SP) ID configured in ESS to use for SSO authentication (optional)
			SamlId *string `json:"saml_id,omitempty"`

			// Template Name of the ESS hardware template to use for the deployment creation (default: gcp-io-optimized-v3)
			Template *string `json:"template,omitempty"`

			// TrustedOrg Trusted ESS organization (Optional)
			TrustedOrg *string `json:"trusted_org,omitempty"`
		} `json:"ess,omitempty"`
		External *struct {
			// Secret Vault secret with the fields to the external Stack (default: '')
			Secret *string `json:"secret,omitempty"`
		} `json:"external,omitempty"`

		// Mode Stack provider, e.g. ess, eck, serverless, external (default: ess)
		Mode *string `json:"mode,omitempty"`

		// Observability True to enable observability features to send logs, metrics, and APM to the monitoring cluster (default: false)
		Observability *bool `json:"observability"`

		// PackageRegistry Package registry to use for the stack.
		PackageRegistry *string `json:"package_registry,omitempty"`
		Serverless      *struct {
			// Cluster ID of the cluster to use for the deployment creation (e.g prd-awsuse1-cp-internal-app-1, qa-awsuse1-cp-internal-app-1)
			Cluster       *string `json:"cluster,omitempty"`
			Elasticsearch *struct {
				// Image Docker image for Elasticsearch (optional)
				Image *string `json:"image,omitempty"`
			} `json:"elasticsearch,omitempty"`
			Fleet *struct {
				// Image Docker image for Fleet (optional)
				Image *string `json:"image,omitempty"`
			} `json:"fleet,omitempty"`
			Kibana *struct {
				// Image Docker image for Kibana (optional)
				Image *string `json:"image,omitempty"`
			} `json:"kibana,omitempty"`

			// Region Cloud region, e.g. gcp-us-central1, aws-eu-west-1, azure-eastus2,  (default: aws-eu-west-1)
			Region *string `json:"region,omitempty"`
		} `json:"serverless,omitempty"`

		// Target Target environment, e.g. production, staging (default: production)
		Target *string `json:"target,omitempty"`

		// Template Name of the template to use for the deployment creation (e.g. elasticsearch, kibana, observability, ccs)
		Template *string `json:"template,omitempty"`

		// UpdateChannel Update channel to use for the stack, e.g. update_channel: unstable, development, release
		UpdateChannel *string `json:"update_channel,omitempty"`

		// UpdateMode Update mode to use for the cluster, e.g. update, recreate (default: update)
		UpdateMode *string `json:"update_mode,omitempty"`

		// UpdateSchedule Update schedule to use for the cluster, e.g. daily, Monday, Tuesday, Wednesday, Thursday, Friday (default: daily)
		UpdateSchedule *string `json:"update_schedule,omitempty"`

		// Version Version of the stack
		Version *string `json:"version,omitempty"`
	} `json:"stack,omitempty"`

	// SyntheticsMonitorsFolders Id of the monitor
	SyntheticsMonitorsFolders *[]struct {
		// Folder Folder where the monitor is located
		Folder *string `json:"folder,omitempty"`

		// Id Id of the monitor
		Id *string `json:"id,omitempty"`

		// Locale Locale to use for the monitor
		Locale *string `json:"locale,omitempty"`

		// Params Parameters to use for the monitor
		Params *map[string]interface{} `json:"params,omitempty"`

		// Timezone Timezone to use for the monitor
		Timezone *string `json:"timezone,omitempty"`
	} `json:"synthetics_monitors_folders,omitempty"`

	// UseSnapshotTfProvider True to use a snapshot version of the Elastic terraform provider (default: false)
	UseSnapshotTfProvider *bool `json:"use_snapshot_tf_provider"`
}

// PostCreateCcsJSONBody defines parameters for PostCreateCcs.
type PostCreateCcsJSONBody struct {
	// Prefix The prefix for the cluster name
	Prefix *string `json:"prefix,omitempty"`

	// RemoteCluster The name of the remote cluster to connect to configure as CCS
	RemoteCluster *string `json:"remote_cluster,omitempty"`

	// Suffix The suffix for the cluster name
	Suffix *string `json:"suffix,omitempty"`
}

// PostCreateCcsJSONRequestBody defines body for PostCreateCcs for application/json ContentType.
type PostCreateCcsJSONRequestBody PostCreateCcsJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostCreateCcsWithBody request with any body
	PostCreateCcsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostCreateCcs(ctx context.Context, body PostCreateCcsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteDestroyClusterName request
	DeleteDestroyClusterName(ctx context.Context, clusterName string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostCreateCcsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCreateCcsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCreateCcs(ctx context.Context, body PostCreateCcsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCreateCcsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteDestroyClusterName(ctx context.Context, clusterName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteDestroyClusterNameRequest(c.Server, clusterName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostCreateCcsRequest calls the generic PostCreateCcs builder with application/json body
func NewPostCreateCcsRequest(server string, body PostCreateCcsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCreateCcsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostCreateCcsRequestWithBody generates requests for PostCreateCcs with any type of body
func NewPostCreateCcsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/create/ccs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteDestroyClusterNameRequest generates requests for DeleteDestroyClusterName
func NewDeleteDestroyClusterNameRequest(server string, clusterName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cluster_name", runtime.ParamLocationPath, clusterName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/destroy/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostCreateCcsWithBodyWithResponse request with any body
	PostCreateCcsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCreateCcsResponse, error)

	PostCreateCcsWithResponse(ctx context.Context, body PostCreateCcsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCreateCcsResponse, error)

	// DeleteDestroyClusterNameWithResponse request
	DeleteDestroyClusterNameWithResponse(ctx context.Context, clusterName string, reqEditors ...RequestEditorFn) (*DeleteDestroyClusterNameResponse, error)
}

type PostCreateCcsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostCreateCcsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCreateCcsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteDestroyClusterNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteDestroyClusterNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteDestroyClusterNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostCreateCcsWithBodyWithResponse request with arbitrary body returning *PostCreateCcsResponse
func (c *ClientWithResponses) PostCreateCcsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCreateCcsResponse, error) {
	rsp, err := c.PostCreateCcsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCreateCcsResponse(rsp)
}

func (c *ClientWithResponses) PostCreateCcsWithResponse(ctx context.Context, body PostCreateCcsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCreateCcsResponse, error) {
	rsp, err := c.PostCreateCcs(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCreateCcsResponse(rsp)
}

// DeleteDestroyClusterNameWithResponse request returning *DeleteDestroyClusterNameResponse
func (c *ClientWithResponses) DeleteDestroyClusterNameWithResponse(ctx context.Context, clusterName string, reqEditors ...RequestEditorFn) (*DeleteDestroyClusterNameResponse, error) {
	rsp, err := c.DeleteDestroyClusterName(ctx, clusterName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteDestroyClusterNameResponse(rsp)
}

// ParsePostCreateCcsResponse parses an HTTP response from a PostCreateCcsWithResponse call
func ParsePostCreateCcsResponse(rsp *http.Response) (*PostCreateCcsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCreateCcsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDeleteDestroyClusterNameResponse parses an HTTP response from a DeleteDestroyClusterNameWithResponse call
func ParseDeleteDestroyClusterNameResponse(rsp *http.Response) (*DeleteDestroyClusterNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteDestroyClusterNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new CCS cluster
	// (POST /create/ccs)
	PostCreateCcs(w http.ResponseWriter, r *http.Request)
	// Destroy a cluster
	// (DELETE /destroy/{cluster_name})
	DeleteDestroyClusterName(w http.ResponseWriter, r *http.Request, clusterName string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostCreateCcs operation middleware
func (siw *ServerInterfaceWrapper) PostCreateCcs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCreateCcs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteDestroyClusterName operation middleware
func (siw *ServerInterfaceWrapper) DeleteDestroyClusterName(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "cluster_name" -------------
	var clusterName string

	err = runtime.BindStyledParameterWithOptions("simple", "cluster_name", r.PathValue("cluster_name"), &clusterName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDestroyClusterName(w, r, clusterName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/create/ccs", wrapper.PostCreateCcs)
	m.HandleFunc("DELETE "+options.BaseURL+"/destroy/{cluster_name}", wrapper.DeleteDestroyClusterName)

	return m
}
