---
- name: Create Docker Secret
  vars:
    k8s_docker_namespace: "{{ item }}"
  k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', '{{ k8s_deployment_dir }}/docker-secret.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
  loop:
    - "{{ k8s_default_namespace }}"
    - "{{ kube_system_namespace }}"
  tags:
    - secrets
    - docker
    - deploy
  when:
    - k8s_enabled | bool
