---
# Description of what the recipe do.
description: Create a temporal kibana_reindex_temp index.
# Path to the REST API call.
api: "/kibana_reindex_temp"
#HTTP method to use it can be GET, POST, PUT, DELETE, ...
method: PUT
# HTTP header we need to pass.
headers:
  Content-Type: application/json
# The payload to send to the REST API.
body: |
  {
      "mappings": {
          "dynamic": false,
          "properties": {}
      }
  }
# The expected return code.
return_code: 200
