---
- name: Delete {{ item.name }} in Google Secret Manager
  ignore_errors: true
  oblt.framework.gcp_secret_manager:
    name: "{{ item.key }}"
    version: all
    state: absent
  register: _result
  loop:
    - name: cluster-state
      key: "{{ cluster_state_gcsm_def_secret }}"
    - name: activate-k8s
      key: "{{ activate_gcsm_def_secret }}"
    - name: env
      key: "{{ elastic_stack_env_gcsm_def_secret }}"
    - name: credentials
      key: "{{ credentials_gcsm_def_secret }}"
    - name: deploy-info
      key: "{{ deploy_info_gcsm_def_secret }}"
    - name: kibana-yml
      key: "{{ kibana_yml_gcsm_def_secret }}"
  tags:
    - secrets
    - delete-config
    - molecule-idempotence-notest
