# minimal helm values for a daemonset

image:
  # -- Docker image of the Elastic Agent.
  name: docker.elastic.co/beats/elastic-agent
  # -- Tag for the Docker image.
  tag: 7.16.2
  # -- Pull Docker images policy [IfNotPresent, Always, Never].
  pullPolicy: IfNotPresent

# -- Command arguments to pass to the Elastic Agent.
commandArgs: [ "-e", "-d", "*" ]

# -- Elastic Agent deployment type [deploymnent, daemonset, standalone]
mode: daemonset

# -- Elastic Agent settings.
fleet:
  # -- token policy name to use for fetching token from Kibana. This requires Kibana configs to be set. This setting is ignored if you provide a `enrollToken`.
  tokenPolicyName: "Default policy"
  # -- To ensure that enrollment occurs on every start of the container set `fleet.force` to true.
  force: true
  # -- set to `true` for enrollment into fleet-server. If not set, Elastic Agent is run in standalone mode.
  enroll: true
  # -- communicate with Fleet with either insecure HTTP or unverified HTTPS.
  insecure: false
  # -- URL of the Fleet Server to enroll into (e.g. https://fleet-server:8220).
  serverUrl: "https://fleet-server:8220"

# -- Kibana settings.
kibana:
  # -- URL of the Kibana (e.g. https://kibana:5601).
  host: "https://kibana:5601"
  # -- Elasticsearch username.
  username: "elastic"
  # -- Elasticsearch password.
  password: "changeme"

fullnameOverride: "mode-daemonset"
