---
- block:
  - name: Copy files to the build dir
    synchronize:
      src: "{{ role_path }}/files/"
      dest: "{{ build_dir }}"
    tags:
      - helm_apps
      - generate_config
      - molecule-idempotence-notest

  - name: Configure Helm Apps
    include_tasks: deploy_apps.yml
    loop: "{{ helm_apps }}"
  when:
    - k8s_enabled|bool
    - (helm_apps|length) > 0
