{{- if .Values.enabled }}
{{- $username := (default "elastic" .Values.db.username) }}
{{- $password := (default "none" .Values.db.password) }}
{{- $dbhost := (default "opbeans-db" .Values.db.host) }}
{{- $dbport := (default "5432" .Values.db.port) }}
{{- $dbname := (default "5432" .Values.db.name) }}
{{- if .Values.db.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opbeans.fullname" .}}-db-creds
type: Opaque
stringData:
{{- if (eq .Values.db.type "mysql") }}
  user: {{ $username }}
  mysql-root-password: {{ $password }}
{{- end }}
{{- if (eq .Values.db.type "postgresql") }}
  user: {{ $username }}
  postgres-password: {{ $password }}
  password: {{ $password }}
  replication-password: {{ $password }}
{{- end }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opbeans.fullname" .}}-config
type: Opaque
stringData:
  OPBEANS_SERVICES: "{{ .Values.opbeans.apiServiceUrl }}"
  OPBEANS_DT_PROBABILITY: "{{ .Values.opbeans.dtProvability }}"
  ELASTIC_APM_LOG_FILE: "{{ .Values.apm.logFile }}"
  REDIS_URL: "{{ .Values.redis.url }}"
  PGHOST: "{{ $dbhost }}"
  PGPORT: "{{ $dbport }}"
  PGUSER: "{{ $username }}"
  PGPASSWORD: "{{ $password }}"
  PGDATABASE: "{{ $dbname }}"
  EXTRA_OPTS: 'breakdownMetrics: true, environment: "testing"'
  DB_DATABASE: "{{ $dbname }}"
  DB_CONNECTION: "pgsql"
  DB_HOST: "{{ $dbhost }}"
  DB_PORT: "{{ $dbport }}"
  DB_USERNAME: "{{ $username }}"
  DB_PASSWORD: "{{ $password }}"
  ELASTIC_APM_LOG_LEVEL: "{{ .Values.apm.logLevel }}"
  ELASTIC_APM_PROFILING_INFERRED_SPANS_ENABLED: "{{ .Values.apm.inferredSpans }}"
  ELASTIC_APM_ENABLE_LOG_CORRELATION: "{{ .Values.apm.logCorrelation }}"
  ELASTIC_APM_VERIFY_SERVER_CERT: "{{ .Values.apm.verifyServerCert }}"
  ELASTIC_APM_TRANSACTION_SAMPLE_RATE: "{{ .Values.apm.transactionRate }}"
  ELASTIC_OPBEANS_API_SERVER: "{{ .Values.opbeans.apiServiceUrl }}"
  OPBEANS_SERVER_PORT: "{{ .Values.opbeans.port }}"
  ELASTIC_APM_ENABLED: "{{ .Values.apm.enabled }}"
  ELASTIC_APM_ACTIVE: "{{ .Values.apm.enabled }}"
{{- if (eq .Values.apm.type "apm") }}
  ELASTIC_APM_SERVER_URL: "{{ .Values.apm.url }}"
  ELASTIC_APM_JS_SERVER_URL: "{{ .Values.apm.url }}"
  ELASTIC_APM_JS_BASE_SERVER_URL: "{{ .Values.apm.url }}"
  ELASTIC_APM_JS_BASE_SERVICE_VERSION: "{{ .Values.apm.serviceVersion }}"
  ELASTIC_APM_SERVICE_VERSION: "{{ .Values.apm.serviceVersion }}"
  {{- if .Values.apm.apikey }}
  ELASTIC_APM_API_KEY: "{{ .Values.apm.apikey }}"
  {{- else if .Values.apm.token }}
  ELASTIC_APM_SECRET_TOKEN: "{{ .Values.apm.token }}"
  {{- end }}
  {{- if .Values.apm.serviceName }}
  ELASTIC_APM_JS_BASE_SERVICE_NAME: "{{ .Values.apm.serviceName }}-frontend"
  ELASTIC_APM_JS_SERVICE_NAME: "{{ .Values.apm.serviceName }}-frontend"
  ELASTIC_APM_SERVICE_NAME: "{{ .Values.apm.serviceName }}"
  {{- end }}
  ELASTIC_APM_ENVIRONMENT: "{{ .Values.apm.environment }}"
{{- end }}
{{- if (eq .Values.apm.type "otel") }}
  OTEL_SDK_DISABLED: "{{ .Values.apm.enabled }}"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.apm.url }}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  APM_AGENT_TYPE: "opentelemetry"
  {{- if .Values.apm.apikey }}
  OTEL_EXPORTER_OTLP_HEADERS: "Authorization=ApiKey {{ .Values.apm.apikey }}"
  {{- else if .Values.apm.token }}
  OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Bearer {{ .Values.apm.token }}"
  {{- end }}
  OTEL_RESOURCE_ATTRIBUTES: service.name={{ .Values.apm.serviceName }},deployment.environment={{ .Values.apm.environment }},service.version="{{ .Values.apm.serviceVersion }}"
{{- end }}
{{- end }}
