{{ if false }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.gcp.project }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.externalSecrets.gcp.clusterLocation }}
          clusterName: {{ .Values.externalSecrets.gcp.clusterName }}
          serviceAccountRef:
            name: external-secrets-default
            namespace: {{ .Values.externalSecrets.namespace }}
{{- end }}
