---
cluster_name: "oblt-test-{{ cluster_seed }}"
save_secrets: false
ephemeral_cluster: true
build_dir: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/build"

observability_secret: "foo"

stack:
  mode: ess
  observability: true
