bootstrap_cluster: true
bootstrap_cluster_dirs:
    - '{{ deployment_dir }}/bootstrap-serverless'
cluster_name: synthetics-billing-audit-serverless
gitops:
    enabled: "true"
    issue: "20472"
    repository: elastic/observability-test-environments
golden_cluster: true
grab_cluster_info: true
oblt_username: robots
slack_channel: '#observablt-bots'
stack:
    mode: serverless
    observability: true
    target: production
    template: observability
updated_at: "2024-02-06T02:12:45Z"
