{{- if and .Values.otelCollector.enabled .Values.otelCollector.elasticsearch.endpoint .Values.otelCollector.elasticsearch.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "megamart-demo.fullname" . }}-elasticsearch
  labels:
    {{- include "megamart-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.otelCollector.elasticsearch.apiKey | quote }}
{{- end }}
