---
- block:
  - name: Create a directory tools folder
    file:
      path: "{{ bin_dir }}"
      state: directory
      mode: 0750

  - name: Install Kubectl CLI
    vars:
      version: "{{ kubectl_version }}"
      arch: "{{ ansible_system | lower }}"
    get_url:
      url: "https://storage.googleapis.com/kubernetes-release/release/v{{ version }}/bin/{{ arch }}/amd64/kubectl"
      dest: "{{ bin_dir }}/kubectl"
      mode: 0770
  when:
    - hermit_enabled is false
  tags:
    - kubectl
    - cli
    - molecule-idempotence-notest

- name: Check tools installed - Kubectl
  changed_when: false
  command: kubectl version --client=true

- name: Set kubectl installed
  file:
    path: "{{ bin_dir }}/kubectl_installed"
    state: touch
  tags:
    - kubectl
    - cli
