# yaml-language-server: $schema=../../../../docs/cluster-config-schema.json
cluster_name: "autopilot-oblt"
golden_cluster: true
slack_channel: "#observablt-bots"
oblt_username: "robots"

k8s:
  provider: autopilot
  static_ip: true

apps:
  k8s:
    - name: App Capacity Reservation
      src: "{{ k8s_deployment_dir }}/capacity-reservation"
  helm:
    - name: kube-state-metrics
      chart: "prometheus-community/kube-state-metrics"
      version: "{{ kube_state_metrics_version }}"
      namespace: "{{ k8s_default_namespace }}"
    - name: kubernetes-integration
      values_file: "{{ helm_deployment_dir }}/elastic_agent/standalone-monitoring-oblt/helm-values.yml.j2"
      chart: "{{ helm_charts_dir }}/elastic_agent_autopilot"
      version: 0.1.0
      namespace: "{{ k8s_default_namespace }}"
