---
- name: Generate ECK Elasticsearch config files
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ build_dir }}/{{ item.file }}"
    mode: 0600
  loop:
    - file: "k8s/elasticsearch/elasticsearch-deployment.yaml"
    - file: "k8s/observability-secrets.yml"
  tags:
    - elasticsearch
    - generate-config-eck
    - molecule-idempotence-notest
