---
- name: Include tasks from copy_files_kibana.yml
  include_tasks: copy_files_kibana.yml

- name: Deploy ECK Kibana
  changed_when: false
  kubernetes.core.k8s:
    namespace: "{{ k8s_default_namespace }}"
    state: present
    src: "{{ k8s_dir }}/kibana/kibana-deployment.yaml"
  tags:
    - kibana
    - deploy

- name: Include tasks from wait_for_kibana.yml
  include_tasks: wait_for_kibana.yml

- name: Include tasks from load_config_kibana.yml
  include_tasks: load_config_kibana.yml

- name: Generate ECK Kibana ingress files
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ build_dir }}/{{ item.file }}"
    mode: 0600
  loop:
    - file: "k8s/kibana/kibana-ingress.yaml"
  when:
    - ingress_available
  tags:
    - kibana
    - generate-config-eck

- name: Deploy ingress Kibana
  kubernetes.core.k8s:
    namespace: "{{ k8s_default_namespace }}"
    state: present
    src: "{{ k8s_dir }}/kibana/kibana-ingress.yaml"
  when:
    - ingress_available
  tags:
    - kibana
    - deploy
