---
- name: Wait for APM
  vars:
    k8s_resource: "pod --selector common.k8s.elastic.co/type=apm-server"
    timeout: 600s
  include_role:
    name: oblt.framework.k8s_common
    tasks_from: wait_for_resource.yml
  when:
    - eck_version is version('2.4.0', '<')
  tags:
    - apm
    - deploy

- name: Wait for APM
  vars:
    k8s_resource: "pod --selector common.k8s.elastic.co/type=agent --selector agent.k8s.elastic.co/name={{ cluster_name }}"
    timeout: 600s
  include_role:
    name: oblt.framework.k8s_common
    tasks_from: wait_for_resource.yml
  when:
    - eck_version is version('2.4.0', '>=')
  tags:
    - agent
    - deploy
