---
apiVersion: vaultproject.io/v1
kind: SecretClaim
metadata:
  name: oblt-robot-secret
  namespace: apm
spec:
  type: Opaque
  path: secret/k8s/elastic-apps/apm/oblt-robot
  renew: 3600
---
apiVersion: vaultproject.io/v1
kind: SecretClaim
metadata:
  name: oblt-robot-elasticsearch-secret
  namespace: apm
spec:
  type: Opaque
  path: secret/k8s/elastic-apps/apm/oblt-robot-elasticsearch
  renew: 3600
---
apiVersion: vaultproject.io/v1
kind: SecretClaim
metadata:
  name: oblt-robot-apm-server-secret
  namespace: apm
spec:
  type: Opaque
  path: secret/k8s/elastic-apps/apm/oblt-robot-apm-server
  renew: 3600
---
apiVersion: vaultproject.io/v1
kind: SecretClaim
metadata:
  name: oblt-robot-gcp-credentials-secret
  namespace: apm
spec:
  type: Opaque
  path: secret/k8s/elastic-apps/apm/oblt-robot-gcp-credentials-secret
  renew: 3600
---
apiVersion: v1
kind: Service
metadata:
  name: oblt-robot
  namespace: apm
spec:
  selector:
    app: oblt-robot-slackbot
  ports:
    - name: oblt-robot
      protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oblt-robot-deployment
  namespace: apm
spec:
  replicas: 4
  selector:
    matchLabels:
      app: oblt-robot-slackbot
  template:
    metadata:
      labels:
        app: oblt-robot-slackbot
    spec:
      containers:
        - name: oblt-robot
          image: docker.elastic.co/observability-ci/oblt-robot:latest
          args: ["--verbose=false"]
          imagePullPolicy: Always
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /home/oblt-robot/oblt-robot-credentials.json
          envFrom:
          - secretRef:
              name: oblt-robot-secret
          - secretRef:
              name: oblt-robot-elasticsearch-secret
          - secretRef:
              name: oblt-robot-apm-server-secret
          volumeMounts:
            - name: gcp-credentials-secret
              mountPath: "/home/oblt-robot/oblt-robot-credentials.json"
              subPath: oblt-robot-credentials.json
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: gcp-credentials-secret
          secret:
            secretName: oblt-robot-gcp-credentials-secret
      restartPolicy: Always
      imagePullSecrets:
        - name: elastic-prod-registry
