---
# https://marketplace.upbound.io/providers/upbound/provider-gcp-secretmanager
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: secretmanager/v1beta1/secretiammember
  labels:
    testing.upbound.io/example-name: example-123
  name: example-123
spec:
  forProvider:
    labels:
      label: my-label
    replication:
      - userManaged:
          - replicas:
              - location: us-central1
  providerConfigRef:
    name: workload-id-providerconfig
---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretVersion
metadata:
  annotations:
    meta.upbound.io/example-id: secretmanager/v1beta1/secretversion
  labels:
    testing.upbound.io/example-name: example-123
  name: secret-version
spec:
  forProvider:
    secret: MySeCrEtPaSsWoRd
    secretDataSecretRef:
      key: secret
      name: secret-version
      namespace: upbound-system
    secretSelector:
      matchLabels:
        testing.upbound.io/example-name: secret-version
  providerConfigRef:
    name: workload-id-providerconfig
