site_name: 'Ansible'
docs_dir: './roles'

nav:
  - './README.md'
  - './ansible-playbooks.md'
  - 'Common': './common/README.md'
  - 'Helm_apps': './helm_apps/README.md'
  - 'k8s_apps': './k8s_apps/README.md'
  - 'k8s_autopilot': './k8s_autopilot/README.md'
  - 'k8s_beats': './k8s_beats/README.md'
  - 'k8s_certmanager': './k8s_certmanager/README.md'
  - 'k8s_gcp': './k8s_gcp/README.md'
  - 'k8s_helm': './k8s_helm/README.md'
  - 'k8s_ingress': './k8s_ingress/README.md'
  - 'k8s_kind': './k8s_kind/README.md'
  - 'k8s_opbeans': './k8s_opbeans/README.md'
  - 'k8s': './k8s/README.md'
  - 'stack_eck': './stack_eck/README.md'
  - 'stack_ess': './stack_ess/README.md'
  - 'stack_security': './stack_security/README.md'
  - 'tools': './tools/README.md'
  - 'vm_gcp': './vm_gcp/README.md'
