apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-node-1
  name: hello-node-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-node-1
  template:
    metadata:
      labels:
        app: hello-node-1
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        name: echoserver
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: false
