---
- name: Configure VM
  include_tasks: copy_files.yml
  tags:
    - configure

- name: "Destroy VM {{ vm_gcp_name }}"
  no_log: false
  environment:
    TF_LOG_PATH: "{{ vm_gcp_terradorm_dir }}/terraform.log"
    TF_LOG: INFO
    TF_IN_AUTOMATION: "1"
  terraform:
    project_path: "{{ vm_gcp_terradorm_dir }}/"
    state: "absent"
    force_init: true
  tags:
    - undeploy
