---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: crossplane-controller-config
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.serviceAccountName }}
spec:
  serviceAccountName: crossplane-default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-default
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.serviceAccountName }}
---
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: workload-id-providerconfig
  namespace: {{ .Values.namespace }}
spec:
  credentials:
    source: InjectedIdentity
  projectID:  {{ .Values.gcp.project }}
