---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elastic-agent.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elastic-agent.labels" . | nindent 4 }}
data:
  agent.yml: |-
{{- if or (eq .Values.mode "standalone") (eq .Values.mode "deployment-standalone") }}
    {{ tpl (.Files.Get "config/elastic-agent-standalone.yaml" | nindent 4) . }}
{{- else }}
    {{ tpl (.Files.Get "config/elastic-agent.yaml" | nindent 4) . }}
{{- end }}
