{{- if and ((.Values.fleetServer).enabled) (empty ((.Values.fleetServer).secretName)) }}
---
apiVersion: v1
data:
  token: {{ required "A service token is required (fleetServer.serviceToken)." .Values.fleetServer.serviceToken | b64enc }}
  policy_id: {{ .Values.fleetServer.policyId | b64enc }}
kind: Secret
metadata:
  name: {{ template "elastic-agent.fleetServerCreds" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- if and (empty ((.Values.fleet).secretName)) (not ((.Values.fleetServer).enabled)) (not (eq .Values.mode "standalone")) (not (eq .Values.mode "deployment-standalone")) }}
---
apiVersion: v1
data:
{{- if ((.Values.fleet).enrollToken) }}
  token: {{ default "" .Values.fleet.enrollToken | b64enc }}
{{- end }}
{{- if ((.Values.fleet).tokenPolicyName) }}
  token_policy_name: {{ default "" .Values.fleet.tokenPolicyName | b64enc }}
{{- end }}
  fleet_server: {{ ((.Values.fleet).serverUrl) | b64enc }}
kind: Secret
metadata:
  name: {{ template "elastic-agent.fleetCreds" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- if and (empty ((.Values.elasticsearch).secretName)) ((.Values.elasticsearch).host) }}
---
apiVersion: v1
data:
  host: {{ ((.Values.elasticsearch).host) | b64enc }}
  username: {{ default "" ((.Values.elasticsearch).username) | b64enc }}
  password: {{ default "" ((.Values.elasticsearch).password) | b64enc }}
  api_token: {{ default "" ((.Values.elasticsearch).apiToken) | b64enc }}
kind: Secret
metadata:
  name: {{ template "elastic-agent.esCreds" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- if and (empty ((.Values.kibana).secretName)) ((.Values.kibana).host) }}
---
apiVersion: v1
data:
  host: {{ ((.Values.kibana).host) | b64enc }}
  username: {{ default "" ((.Values.kibana).username) | b64enc }}
  password: {{ default "" ((.Values.kibana).password) | b64enc }}
kind: Secret
metadata:
  name: {{ template "elastic-agent.kibanaCreds" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
