---
cluster_name: "oblt-test-{{ cluster_seed }}"
deploy_timestamp: none
ephemeral_cluster: true
build_dir: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/build"

stack:
  mode: eck
  template: observability
  certmanager: false
  ingress: false

k8s:
  provider: kind

opbeans:
  enabled: true
