---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-contrib
  labels:
    app: opentelemetry
    component: otel-collector-contrib
spec:
  type: ClusterIP
  selector:
    component: otel-collector-contrib
  ports:
    - name: zpages
      protocol: TCP
      port: 55679
      targetPort: 55679
    - name: metrics
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: apm-exporter
      protocol: TCP
      port: 8200
      targetPort: 8200
    - name: gprc
      protocol: TCP
      port: 4317
      targetPort: 4317
