---
## Workflow update oblt clusters on channels updates.
name: Oblt Cluster update-channels
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag ref to run the workflow on'
        required: true
        default: 'main'
  push:
    branches:
      - main
    paths:
      - '.ci/update-versions/update_channels.json'

permissions:
  pull-requests: write
  contents: write

jobs:
  channel-changes:
    runs-on: ubuntu-latest
    outputs:
      changedChannels: ${{ steps.changed-channels.outputs.changedChannels }}
      currentChannels: ${{ steps.changed-channels.outputs.currentChannels }}
      previousChannels: ${{ steps.changed-channels.outputs.previousChannels }}
      dayOfWeek: ${{ steps.changed-channels.outputs.dayOfWeek }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          ref: ${{ inputs.ref || github.sha || 'main' }}
      - uses: ./.github/actions/channel-changes
        id: changed-channels
        with:
          ref: ${{ inputs.ref || github.sha || 'main' }}
  docker-images-stack:
    if: ${{ fromJSON(needs.channel-changes.outputs.changedChannels)[0] != '' }}
    runs-on: ubuntu-latest
    needs:
      - channel-changes
    strategy:
      fail-fast: false
      matrix:
        channel: ${{ fromJson(needs.channel-changes.outputs.changedChannels) }}
    env:
      CHANNEL: ${{ matrix.channel }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          ref: ${{ inputs.ref || github.sha || 'main' }}

      # IMPORTANT: the secrets below are managed through IASC (contact robots if you need further assistance)
      - name: Log in to the Elastic Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ secrets.ELASTIC_DOCKER_REGISTRY }}
          username: ${{ secrets.ELASTIC_DOCKER_USERNAME }}
          password: ${{ secrets.ELASTIC_DOCKER_PASSWORD }}
      - name: Get Docker images
        run: |
          STACK_VERSION=$(jq -r ".\"${CHANNEL}\".version" .ci/update-versions/update_channels.json)
          STACK_BUILD=$(jq -r ".\"${CHANNEL}\".build" .ci/update-versions/update_channels.json)
          if [ "${STACK_VERSION}" != "serverless" ]; then
            .ci/scripts/getDockerImages.sh "${STACK_VERSION}" 'observability-ci' "${STACK_BUILD}"
          fi
  clusters-to-update:
    if: ${{ fromJSON(needs.channel-changes.outputs.changedChannels)[0] != '' }}
    runs-on: ubuntu-latest
    needs:
      - channel-changes
      - docker-images-stack
    strategy:
      fail-fast: false
      matrix:
        channel: ${{ fromJson(needs.channel-changes.outputs.changedChannels) }}
    env:
      CHANNEL: ${{ matrix.channel }}
      DAY_OF_WEEK: ${{ needs.channel-changes.outputs.dayOfWeek }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          ref: ${{ inputs.ref || github.sha || 'main' }}
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: 'pip'
          cache-dependency-path: ansible/requirements.txt
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2.65.0"
        with:
          version: "v0.75.0"
      - name: Setup Git
        uses: elastic/oblt-actions/git/setup@v1
      - name: "Search for clusters in the release update ${{ matrix.channel }}"
        uses: elastic/oblt-actions/oblt-cli/run@v1
        with:
          command: 'cluster list --filter "stack.update_channel=${CHANNEL}" --output-file ${PWD}/updates.json || true'
          github-token: ${{ secrets.OBLT_TEST_ENV_GITHUB_TOKEN }}
      - name: "Update clusters"
        run: |
          # shellcheck disable=SC2086
          for CLUSTER_CONFIG in $(jq -r '.items[]|.clusterConfigPath' updates.json);
          do
            UPDATE_SCHEDULE=$(yq -r '.stack.update_schedule' "${CLUSTER_CONFIG}")
            STACK_MODE=$(yq -r '.stack.mode' "${CLUSTER_CONFIG}"||echo "ess")
            cluster_name=$(yq -r '.cluster_name' "${CLUSTER_CONFIG}")
            if [ -z "${UPDATE_SCHEDULE}" ] || [ "${UPDATE_SCHEDULE}" = "null" ]; then
              UPDATE_SCHEDULE="daily"
            fi

            # Check if the update schedule is daily or today is the day of the week
            if [ "${UPDATE_SCHEDULE}" = "daily" ]; then
              WARNING="::warning title=Failed to update::The cluster ${cluster_name} failed to update."
              make -C .ci/update-versions "update-elastic-stack-${STACK_MODE}" CLUSTER_NAME="${cluster_name}" || echo "${WARNING}"
            else
              echo "Skipping update of ${cluster_name} because it is scheduled for ${UPDATE_SCHEDULE} and today is ${DAY_OF_WEEK}"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.OBLT_TEST_ENV_GITHUB_TOKEN }}
