---
name: Oblt Cluster CCS (issue)

on:
  issues:
    types:
      - edited
      - opened

permissions:
  contents: read
  issues: write

# Avoid running if there is already an on-going action running for the same
# GitHub issue
concurrency:
  group: "${{ github.workflow }}-${{ github.event.issue.number }}"

jobs:
  ccs_cluster:
    if: contains(github.event.issue.labels.*.name, 'ccs-cluster')
    runs-on: ubuntu-latest
    steps:
      - name: Notify - started
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🏃 I am attending your request for creating your custom CCS cluster ([logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}))'
            })
      - uses: actions/checkout@v6

      # Use https://github.com/stefanbuck/github-issue-parser/releases/tag/v3.0.1
      - uses: stefanbuck/github-issue-parser@c1a559d78bfb8dd05216dab9ffd2b91082ff5324
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/cluster-ccs-issue.yaml

      - uses: elastic/oblt-actions/git/setup@v1
      - uses: elastic/oblt-actions/oblt-cli/cluster-create-ccs@v1
        with:
          username: ${{ github.event.issue.user.login }}
          github-token: ${{ secrets.OBLT_TEST_ENV_GITHUB_TOKEN }}
          remote-cluster: ${{ steps.issue-parser.outputs.issueparser_template }}
          cluster-name-prefix: ${{ steps.issue-parser.outputs.issueparser_prefix || 'issue' }}
          cluster-name-suffix: ${{ steps.issue-parser.outputs.issueparser_suffix || '' }}
          gitops: true
