---
## Workflow to listen for any deployment failure and create the relevant GitHub issue.
## See https://github.com/elastic/observability-test-environments/pull/33959 that
## explains the rationale behind this workflow.
name: failed-deployment
on:
  workflow_run:
    workflows:
      - Oblt Cluster manager
    types:
      - completed

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    env:
      # Env variables to pass the context of this workflow run
      # so the GitHub issue can be created with the relevant information
      # And the automation in observability-system-status can download the artifacts.
      ARTIFACT_NAME: artifacts
      WORKFLOW_NAME: failed-deployment.yml
    steps:
      - uses: actions/checkout@v6
      - name: Fetch artifacts
        id: download
        uses: dawidd6/action-download-artifact@1f8785ff7a5130826f848e7f72725c85d241860f # v18
        with:
          github_token: ${{ secrets.OBLT_TEST_ENV_GITHUB_TOKEN }}
          workflow: cluster-manager.yml
          workflow_conclusion: failure
          if_no_artifact_found: warn
          path: downloaded-artifacts

      - name: Debug
        run: |
          echo "Downloaded artifact: ${{ steps.download.outputs.artifacts }}"
          echo "found_artifact: ${{ steps.download.outputs.found_artifact }}"
          echo "error_message: ${{ steps.download.outputs.error_message }}"
          echo "dry_run: ${{ steps.download.outputs.dry_run }}"
          find downloaded-artifacts -type f

      - name: Search config file
        id: config-file
        if: ${{ steps.download.outputs.found_artifact == 'true' }}
        run: |
          CONFIG_FILE=$(find downloaded-artifacts -type f -name "config-cluster.yml")
          echo "CONFIG_FILE: $CONFIG_FILE"
          echo "config_file=$CONFIG_FILE" >> "$GITHUB_OUTPUT"

      - name: Read cluster config
        id: cluster-config
        if: ${{ steps.download.outputs.found_artifact == 'true' && steps.config-file.outputs.config_file != '' }}
        uses: ./.github/actions/cluster-read-config
        with:
          filename: ${{ steps.config-file.outputs.config_file }}

      # Store artifacts to be consumed later on by the observability-system-status automation
      - uses: actions/upload-artifact@v7
        if: ${{ steps.download.outputs.found_artifact == 'true' && steps.config-file.outputs.config_file != '' }}
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: downloaded-artifacts

      - name: Generate GitHub issue
        if: ${{ steps.download.outputs.found_artifact == 'true' && steps.config-file.outputs.config_file != '' }}
        run: |
          GITHUB_ISSUE=$(mktemp --suffix ".md")
          cat <<EOF > "$GITHUB_ISSUE"
          ### Name

          ${{ steps.cluster-config.outputs.cluster_name }}

          ### APM

          ${{ steps.cluster-config.outputs.apm_version }}

          ### Elasticsearch

          ${{ steps.cluster-config.outputs.elasticsearch_version }}

          ### Kibana

          ${{ steps.cluster-config.outputs.kibana_version }}

          ### Golden cluster

          ${{ steps.cluster-config.outputs.golden_cluster }}

          ### Stack version

          ${{ steps.cluster-config.outputs.stack_version }}

          ### Build version

          ${{ steps.cluster-config.outputs.stack_build }}

          ### Workflow name

          ${{ env.WORKFLOW_NAME }}

          ### Workflow run

          ${{ github.run_id }}

          ### Artifact

          ${{ env.ARTIFACT_NAME }}

          ### Further details
          Generated by ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}
          EOF

          ## TODO: upload the content of some files? (e.g. logs, etc.)
          gh issue create \
            --title "deployment failed for ${{ steps.cluster-config.outputs.cluster_name }}" \
            --label "failed-deployment" \
            --body-file "${GITHUB_ISSUE}" \
            --repo 'elastic/observability-system-status'
        env:
          GH_TOKEN: ${{ secrets.OBLT_TEST_ENV_GITHUB_TOKEN }}
