---
name: lint GitHub Actions

on:
  pull_request:
    paths:
      - '.github/workflows/**'

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Check workflow files
      uses: docker://rhysd/actionlint:latest
      with:
        args: -color
