---
## Workflow to daily update Helm charts.
name: update-helm-charts
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1-5"

permissions:
  pull-requests: write
  contents: write

jobs:
  helm-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2.65.0"
        with:
          version: "v0.75.0"
      - uses: elastic/oblt-actions/git/setup@v1
        with:
          github-token: ${{ secrets.OBLT_TEST_ENV_GITHUB_TOKEN }}
      - run: make -C .ci/update-versions update-helm-charts
        env:
          GITHUB_TOKEN: ${{ secrets.OBLT_TEST_ENV_GITHUB_TOKEN }}
